/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bedam;

import javax.swing.JOptionPane;

/**
 *
 * @author benr0
 */
public class CancelBookingJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CancelBookingJFrame
     */
    public CancelBookingJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        cancelTitle = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        bookingNumTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(172, 140, 71));
        titleLabel.setText("About Us");
        titleLabel.setRequestFocusEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(942, 564));

        cancelTitle.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        cancelTitle.setForeground(new java.awt.Color(172, 140, 71));
        cancelTitle.setText("Cancel Booking");
        cancelTitle.setRequestFocusEnabled(false);

        infoLabel.setText("Enter your booking number below:");

        bookingNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingNumTextFieldActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel Booking");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel)
                    .addComponent(cancelTitle))
                .addGap(349, 349, 349))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(bookingNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(cancelTitle)
                .addGap(64, 64, 64)
                .addComponent(infoLabel)
                .addGap(36, 36, 36)
                .addComponent(bookingNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingNumTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        BedamJFrame.main(null);
        CancelBookingJFrame.super.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        String bNumString = bookingNumTextField.getText();
        try {
            int bookingNum = Integer.parseInt(bNumString);
            if (DatabaseBedam.checkBookingNumInDB(bookingNum)) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel this booking?\nPlease note there are no refunds.", "Cancel Booking", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    DatabaseBedam.removeBookingFromDB(bookingNum);
                    JOptionPane.showMessageDialog(null, "Booking cancelled!", "Booking cancelled", JOptionPane.INFORMATION_MESSAGE);
                    
                        backButtonActionPerformed(null);
                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Order number doesn't exist!");
            }
        } catch (NumberFormatException e) {
          //  System.out.println("err");
            JOptionPane.showMessageDialog(null, "Invalid input");
            bookingNumTextField.setText("");
        }
//        DatabaseBedam.removeBookingFromDB(HEIGHT);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new CancelBookingJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bookingNumTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cancelTitle;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
